// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTestimonial = `-- name: CreateTestimonial :one
INSERT INTO testimonials (name, email, heading, content, is_approved, is_published)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, heading, content, is_approved, is_published, created_at, updated_at
`

type CreateTestimonialParams struct {
	Name        string      `json:"name"`
	Email       pgtype.Text `json:"email"`
	Heading     string      `json:"heading"`
	Content     string      `json:"content"`
	IsApproved  bool        `json:"is_approved"`
	IsPublished bool        `json:"is_published"`
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (Testimonial, error) {
	row := q.db.QueryRow(ctx, createTestimonial,
		arg.Name,
		arg.Email,
		arg.Heading,
		arg.Content,
		arg.IsApproved,
		arg.IsPublished,
	)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Heading,
		&i.Content,
		&i.IsApproved,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminSettingByKey = `-- name: GetAdminSettingByKey :one
SELECT id, setting_key, setting_value, updated_at, updated_by FROM admin_settings WHERE setting_key = $1 LIMIT 1
`

func (q *Queries) GetAdminSettingByKey(ctx context.Context, settingKey string) (AdminSetting, error) {
	row := q.db.QueryRow(ctx, getAdminSettingByKey, settingKey)
	var i AdminSetting
	err := row.Scan(
		&i.ID,
		&i.SettingKey,
		&i.SettingValue,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listTestimonials = `-- name: ListTestimonials :many
SELECT id, name, email, heading, content, is_approved, is_published, created_at, updated_at FROM testimonials ORDER BY created_at DESC
`

func (q *Queries) ListTestimonials(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testimonial{}
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Heading,
			&i.Content,
			&i.IsApproved,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTestimonialApproval = `-- name: UpdateTestimonialApproval :one
UPDATE testimonials
SET is_approved = $2, is_published = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, heading, content, is_approved, is_published, created_at, updated_at
`

type UpdateTestimonialApprovalParams struct {
	ID          uuid.UUID `json:"id"`
	IsApproved  bool      `json:"is_approved"`
	IsPublished bool      `json:"is_published"`
}

func (q *Queries) UpdateTestimonialApproval(ctx context.Context, arg UpdateTestimonialApprovalParams) (Testimonial, error) {
	row := q.db.QueryRow(ctx, updateTestimonialApproval, arg.ID, arg.IsApproved, arg.IsPublished)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Heading,
		&i.Content,
		&i.IsApproved,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdminSetting = `-- name: UpsertAdminSetting :one
INSERT INTO admin_settings (setting_key, setting_value, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (setting_key)
DO UPDATE SET setting_value = EXCLUDED.setting_value, updated_by = EXCLUDED.updated_by, updated_at = NOW()
RETURNING id, setting_key, setting_value, updated_at, updated_by
`

type UpsertAdminSettingParams struct {
	SettingKey   string      `json:"setting_key"`
	SettingValue []byte      `json:"setting_value"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertAdminSetting(ctx context.Context, arg UpsertAdminSettingParams) (AdminSetting, error) {
	row := q.db.QueryRow(ctx, upsertAdminSetting, arg.SettingKey, arg.SettingValue, arg.UpdatedBy)
	var i AdminSetting
	err := row.Scan(
		&i.ID,
		&i.SettingKey,
		&i.SettingValue,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
