// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedSurveysByCampaign = `-- name: CountCompletedSurveysByCampaign :one
SELECT COUNT(DISTINCT u.id)
FROM users u
JOIN survey_responses sr ON sr.user_id = u.id
WHERE sr.campaign_id = $1 AND u.survey_completed = TRUE
`

func (q *Queries) CountCompletedSurveysByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedSurveysByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParticipantsByCampaign = `-- name: CountParticipantsByCampaign :one
SELECT COUNT(DISTINCT user_id) FROM survey_responses WHERE campaign_id = $1
`

func (q *Queries) CountParticipantsByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipantsByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    name,
    survey_open_date,
    survey_close_date,
    profile_update_start_date,
    profile_update_end_date,
    results_release_date,
    is_active,
    config,
    algorithm_version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, survey_open_date, survey_close_date, profile_update_start_date, profile_update_end_date, results_release_date, is_active, total_participants, total_matches_generated, algorithm_version, config, created_at
`

type CreateCampaignParams struct {
	Name                   string      `json:"name"`
	SurveyOpenDate         time.Time   `json:"survey_open_date"`
	SurveyCloseDate        time.Time   `json:"survey_close_date"`
	ProfileUpdateStartDate time.Time   `json:"profile_update_start_date"`
	ProfileUpdateEndDate   time.Time   `json:"profile_update_end_date"`
	ResultsReleaseDate     time.Time   `json:"results_release_date"`
	IsActive               pgtype.Bool `json:"is_active"`
	Config                 []byte      `json:"config"`
	AlgorithmVersion       pgtype.Text `json:"algorithm_version"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.SurveyOpenDate,
		arg.SurveyCloseDate,
		arg.ProfileUpdateStartDate,
		arg.ProfileUpdateEndDate,
		arg.ResultsReleaseDate,
		arg.IsActive,
		arg.Config,
		arg.AlgorithmVersion,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SurveyOpenDate,
		&i.SurveyCloseDate,
		&i.ProfileUpdateStartDate,
		&i.ProfileUpdateEndDate,
		&i.ResultsReleaseDate,
		&i.IsActive,
		&i.TotalParticipants,
		&i.TotalMatchesGenerated,
		&i.AlgorithmVersion,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getActiveCampaign = `-- name: GetActiveCampaign :one
SELECT id, name, survey_open_date, survey_close_date, profile_update_start_date, profile_update_end_date, results_release_date, is_active, total_participants, total_matches_generated, algorithm_version, config, created_at FROM campaigns WHERE is_active = TRUE ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveCampaign(ctx context.Context) (Campaign, error) {
	row := q.db.QueryRow(ctx, getActiveCampaign)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SurveyOpenDate,
		&i.SurveyCloseDate,
		&i.ProfileUpdateStartDate,
		&i.ProfileUpdateEndDate,
		&i.ResultsReleaseDate,
		&i.IsActive,
		&i.TotalParticipants,
		&i.TotalMatchesGenerated,
		&i.AlgorithmVersion,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, survey_open_date, survey_close_date, profile_update_start_date, profile_update_end_date, results_release_date, is_active, total_participants, total_matches_generated, algorithm_version, config, created_at FROM campaigns WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SurveyOpenDate,
		&i.SurveyCloseDate,
		&i.ProfileUpdateStartDate,
		&i.ProfileUpdateEndDate,
		&i.ResultsReleaseDate,
		&i.IsActive,
		&i.TotalParticipants,
		&i.TotalMatchesGenerated,
		&i.AlgorithmVersion,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, survey_open_date, survey_close_date, profile_update_start_date, profile_update_end_date, results_release_date, is_active, total_participants, total_matches_generated, algorithm_version, config, created_at FROM campaigns ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SurveyOpenDate,
			&i.SurveyCloseDate,
			&i.ProfileUpdateStartDate,
			&i.ProfileUpdateEndDate,
			&i.ResultsReleaseDate,
			&i.IsActive,
			&i.TotalParticipants,
			&i.TotalMatchesGenerated,
			&i.AlgorithmVersion,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns SET
    name = COALESCE($2, name),
    survey_open_date = COALESCE($3, survey_open_date),
    survey_close_date = COALESCE($4, survey_close_date),
    profile_update_start_date = COALESCE($5, profile_update_start_date),
    profile_update_end_date = COALESCE($6, profile_update_end_date),
    results_release_date = COALESCE($7, results_release_date),
    is_active = COALESCE($8, is_active),
    config = COALESCE($9, config),
    algorithm_version = COALESCE($10, algorithm_version)
WHERE id = $1
RETURNING id, name, survey_open_date, survey_close_date, profile_update_start_date, profile_update_end_date, results_release_date, is_active, total_participants, total_matches_generated, algorithm_version, config, created_at
`

type UpdateCampaignParams struct {
	ID                     uuid.UUID   `json:"id"`
	Name                   string      `json:"name"`
	SurveyOpenDate         time.Time   `json:"survey_open_date"`
	SurveyCloseDate        time.Time   `json:"survey_close_date"`
	ProfileUpdateStartDate time.Time   `json:"profile_update_start_date"`
	ProfileUpdateEndDate   time.Time   `json:"profile_update_end_date"`
	ResultsReleaseDate     time.Time   `json:"results_release_date"`
	IsActive               pgtype.Bool `json:"is_active"`
	Config                 []byte      `json:"config"`
	AlgorithmVersion       pgtype.Text `json:"algorithm_version"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Name,
		arg.SurveyOpenDate,
		arg.SurveyCloseDate,
		arg.ProfileUpdateStartDate,
		arg.ProfileUpdateEndDate,
		arg.ResultsReleaseDate,
		arg.IsActive,
		arg.Config,
		arg.AlgorithmVersion,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SurveyOpenDate,
		&i.SurveyCloseDate,
		&i.ProfileUpdateStartDate,
		&i.ProfileUpdateEndDate,
		&i.ResultsReleaseDate,
		&i.IsActive,
		&i.TotalParticipants,
		&i.TotalMatchesGenerated,
		&i.AlgorithmVersion,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const updateCampaignStats = `-- name: UpdateCampaignStats :exec
UPDATE campaigns SET
    total_participants = $2,
    total_matches_generated = $3
WHERE id = $1
`

type UpdateCampaignStatsParams struct {
	ID                    uuid.UUID   `json:"id"`
	TotalParticipants     pgtype.Int4 `json:"total_participants"`
	TotalMatchesGenerated pgtype.Int4 `json:"total_matches_generated"`
}

func (q *Queries) UpdateCampaignStats(ctx context.Context, arg UpdateCampaignStatsParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStats, arg.ID, arg.TotalParticipants, arg.TotalMatchesGenerated)
	return err
}
