// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interactions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createInteraction = `-- name: CreateInteraction :one
INSERT INTO interactions (match_id, user_id, interaction_type, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, match_id, user_id, interaction_type, metadata, created_at
`

type CreateInteractionParams struct {
	MatchID         uuid.UUID `json:"match_id"`
	UserID          uuid.UUID `json:"user_id"`
	InteractionType string    `json:"interaction_type"`
	Metadata        []byte    `json:"metadata"`
}

func (q *Queries) CreateInteraction(ctx context.Context, arg CreateInteractionParams) (Interaction, error) {
	row := q.db.QueryRow(ctx, createInteraction,
		arg.MatchID,
		arg.UserID,
		arg.InteractionType,
		arg.Metadata,
	)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.InteractionType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const findInterestByMatchOtherUser = `-- name: FindInterestByMatchOtherUser :one
SELECT id, match_id, user_id, interaction_type, metadata, created_at FROM interactions
WHERE match_id = $1 AND user_id <> $2 AND interaction_type = 'interest'
LIMIT 1
`

type FindInterestByMatchOtherUserParams struct {
	MatchID uuid.UUID `json:"match_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) FindInterestByMatchOtherUser(ctx context.Context, arg FindInterestByMatchOtherUserParams) (Interaction, error) {
	row := q.db.QueryRow(ctx, findInterestByMatchOtherUser, arg.MatchID, arg.UserID)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.InteractionType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
