// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matching.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCrushByUserEmailCampaign = `-- name: CountCrushByUserEmailCampaign :one
SELECT COUNT(*) FROM crush_lists
WHERE user_id = $1 AND campaign_id = $2 AND crush_email = $3
`

type CountCrushByUserEmailCampaignParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
	CrushEmail string    `json:"crush_email"`
}

func (q *Queries) CountCrushByUserEmailCampaign(ctx context.Context, arg CountCrushByUserEmailCampaignParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrushByUserEmailCampaign, arg.UserID, arg.CampaignID, arg.CrushEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSurveyResponsesWithQuestionsByUserCampaign = `-- name: ListSurveyResponsesWithQuestionsByUserCampaign :many
SELECT
    sr.id,
    sr.user_id,
    sr.campaign_id,
    sr.question_id,
    sr.answer_text,
    sr.answer_value,
    sr.answer_json,
    sr.answer_type,
    sr.created_at,
    sr.updated_at,
    q.category AS question_category,
    q.weight AS question_weight
FROM survey_responses sr
JOIN questions q ON q.id = sr.question_id
WHERE sr.user_id = $1 AND sr.campaign_id = $2
`

type ListSurveyResponsesWithQuestionsByUserCampaignParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

type ListSurveyResponsesWithQuestionsByUserCampaignRow struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	CampaignID       pgtype.UUID    `json:"campaign_id"`
	QuestionID       uuid.UUID      `json:"question_id"`
	AnswerText       pgtype.Text    `json:"answer_text"`
	AnswerValue      pgtype.Int4    `json:"answer_value"`
	AnswerJson       []byte         `json:"answer_json"`
	AnswerType       string         `json:"answer_type"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	QuestionCategory string         `json:"question_category"`
	QuestionWeight   pgtype.Numeric `json:"question_weight"`
}

func (q *Queries) ListSurveyResponsesWithQuestionsByUserCampaign(ctx context.Context, arg ListSurveyResponsesWithQuestionsByUserCampaignParams) ([]ListSurveyResponsesWithQuestionsByUserCampaignRow, error) {
	rows, err := q.db.Query(ctx, listSurveyResponsesWithQuestionsByUserCampaign, arg.UserID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSurveyResponsesWithQuestionsByUserCampaignRow{}
	for rows.Next() {
		var i ListSurveyResponsesWithQuestionsByUserCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CampaignID,
			&i.QuestionID,
			&i.AnswerText,
			&i.AnswerValue,
			&i.AnswerJson,
			&i.AnswerType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionCategory,
			&i.QuestionWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
