// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: matches.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, campaign_id, user1_id, user2_id, compatibility_score, match_tier, shared_interests, rank_for_user1, rank_for_user2, is_revealed, is_mutual_interest, is_mutual_crush, messaging_unlocked, created_at, revealed_at, updated_at FROM matches WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.User1ID,
		&i.User2ID,
		&i.CompatibilityScore,
		&i.MatchTier,
		&i.SharedInterests,
		&i.RankForUser1,
		&i.RankForUser2,
		&i.IsRevealed,
		&i.IsMutualInterest,
		&i.IsMutualCrush,
		&i.MessagingUnlocked,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchesForUser = `-- name: ListMatchesForUser :many
SELECT id, campaign_id, user1_id, user2_id, compatibility_score, match_tier, shared_interests, rank_for_user1, rank_for_user2, is_revealed, is_mutual_interest, is_mutual_crush, messaging_unlocked, created_at, revealed_at, updated_at FROM matches WHERE user1_id = $1 OR user2_id = $1 ORDER BY compatibility_score DESC
`

func (q *Queries) ListMatchesForUser(ctx context.Context, user1ID uuid.UUID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesForUser, user1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.User1ID,
			&i.User2ID,
			&i.CompatibilityScore,
			&i.MatchTier,
			&i.SharedInterests,
			&i.RankForUser1,
			&i.RankForUser2,
			&i.IsRevealed,
			&i.IsMutualInterest,
			&i.IsMutualCrush,
			&i.MessagingUnlocked,
			&i.CreatedAt,
			&i.RevealedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revealMatch = `-- name: RevealMatch :one
UPDATE matches SET is_revealed = TRUE, revealed_at = NOW() WHERE id = $1 RETURNING id, campaign_id, user1_id, user2_id, compatibility_score, match_tier, shared_interests, rank_for_user1, rank_for_user2, is_revealed, is_mutual_interest, is_mutual_crush, messaging_unlocked, created_at, revealed_at, updated_at
`

func (q *Queries) RevealMatch(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, revealMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.User1ID,
		&i.User2ID,
		&i.CompatibilityScore,
		&i.MatchTier,
		&i.SharedInterests,
		&i.RankForUser1,
		&i.RankForUser2,
		&i.IsRevealed,
		&i.IsMutualInterest,
		&i.IsMutualCrush,
		&i.MessagingUnlocked,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMatchInterest = `-- name: UpdateMatchInterest :one
UPDATE matches
SET
    is_mutual_interest = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, campaign_id, user1_id, user2_id, compatibility_score, match_tier, shared_interests, rank_for_user1, rank_for_user2, is_revealed, is_mutual_interest, is_mutual_crush, messaging_unlocked, created_at, revealed_at, updated_at
`

type UpdateMatchInterestParams struct {
	ID               uuid.UUID `json:"id"`
	IsMutualInterest bool      `json:"is_mutual_interest"`
}

func (q *Queries) UpdateMatchInterest(ctx context.Context, arg UpdateMatchInterestParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchInterest, arg.ID, arg.IsMutualInterest)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.User1ID,
		&i.User2ID,
		&i.CompatibilityScore,
		&i.MatchTier,
		&i.SharedInterests,
		&i.RankForUser1,
		&i.RankForUser2,
		&i.IsRevealed,
		&i.IsMutualInterest,
		&i.IsMutualCrush,
		&i.MessagingUnlocked,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.UpdatedAt,
	)
	return i, err
}
