// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches_admin.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMatchesAll = `-- name: CountMatchesAll :one
SELECT COUNT(*) FROM matches
`

func (q *Queries) CountMatchesAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    campaign_id,
    user1_id,
    user2_id,
    compatibility_score,
    match_tier,
    shared_interests,
    rank_for_user1,
    rank_for_user2,
    is_mutual_crush,
    is_revealed
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, campaign_id, user1_id, user2_id, compatibility_score, match_tier, shared_interests, rank_for_user1, rank_for_user2, is_revealed, is_mutual_interest, is_mutual_crush, messaging_unlocked, created_at, revealed_at, updated_at
`

type CreateMatchParams struct {
	CampaignID         pgtype.UUID    `json:"campaign_id"`
	User1ID            uuid.UUID      `json:"user1_id"`
	User2ID            uuid.UUID      `json:"user2_id"`
	CompatibilityScore pgtype.Numeric `json:"compatibility_score"`
	MatchTier          pgtype.Text    `json:"match_tier"`
	SharedInterests    []byte         `json:"shared_interests"`
	RankForUser1       pgtype.Int4    `json:"rank_for_user1"`
	RankForUser2       pgtype.Int4    `json:"rank_for_user2"`
	IsMutualCrush      bool           `json:"is_mutual_crush"`
	IsRevealed         bool           `json:"is_revealed"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.CampaignID,
		arg.User1ID,
		arg.User2ID,
		arg.CompatibilityScore,
		arg.MatchTier,
		arg.SharedInterests,
		arg.RankForUser1,
		arg.RankForUser2,
		arg.IsMutualCrush,
		arg.IsRevealed,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.User1ID,
		&i.User2ID,
		&i.CompatibilityScore,
		&i.MatchTier,
		&i.SharedInterests,
		&i.RankForUser1,
		&i.RankForUser2,
		&i.IsRevealed,
		&i.IsMutualInterest,
		&i.IsMutualCrush,
		&i.MessagingUnlocked,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches WHERE id = $1
`

func (q *Queries) DeleteMatch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMatch, id)
	return err
}

const deleteMatchesByCampaign = `-- name: DeleteMatchesByCampaign :exec
DELETE FROM matches WHERE campaign_id = $1
`

func (q *Queries) DeleteMatchesByCampaign(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMatchesByCampaign, campaignID)
	return err
}

const listMatches = `-- name: ListMatches :many
SELECT id, campaign_id, user1_id, user2_id, compatibility_score, match_tier, shared_interests, rank_for_user1, rank_for_user2, is_revealed, is_mutual_interest, is_mutual_crush, messaging_unlocked, created_at, revealed_at, updated_at FROM matches ORDER BY compatibility_score DESC LIMIT $1 OFFSET $2
`

type ListMatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMatches(ctx context.Context, arg ListMatchesParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.User1ID,
			&i.User2ID,
			&i.CompatibilityScore,
			&i.MatchTier,
			&i.SharedInterests,
			&i.RankForUser1,
			&i.RankForUser2,
			&i.IsRevealed,
			&i.IsMutualInterest,
			&i.IsMutualCrush,
			&i.MessagingUnlocked,
			&i.CreatedAt,
			&i.RevealedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockMessagingByCampaign = `-- name: UnlockMessagingByCampaign :exec
UPDATE matches SET messaging_unlocked = TRUE, updated_at = NOW()
WHERE campaign_id = $1
`

func (q *Queries) UnlockMessagingByCampaign(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlockMessagingByCampaign, campaignID)
	return err
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches
SET
    compatibility_score = COALESCE($2, compatibility_score),
    match_tier = COALESCE($3, match_tier),
    is_revealed = COALESCE($4, is_revealed),
    updated_at = NOW()
WHERE id = $1
RETURNING id, campaign_id, user1_id, user2_id, compatibility_score, match_tier, shared_interests, rank_for_user1, rank_for_user2, is_revealed, is_mutual_interest, is_mutual_crush, messaging_unlocked, created_at, revealed_at, updated_at
`

type UpdateMatchParams struct {
	ID                 uuid.UUID      `json:"id"`
	CompatibilityScore pgtype.Numeric `json:"compatibility_score"`
	MatchTier          pgtype.Text    `json:"match_tier"`
	IsRevealed         bool           `json:"is_revealed"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.ID,
		arg.CompatibilityScore,
		arg.MatchTier,
		arg.IsRevealed,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.User1ID,
		&i.User2ID,
		&i.CompatibilityScore,
		&i.MatchTier,
		&i.SharedInterests,
		&i.RankForUser1,
		&i.RankForUser2,
		&i.IsRevealed,
		&i.IsMutualInterest,
		&i.IsMutualCrush,
		&i.MessagingUnlocked,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.UpdatedAt,
	)
	return i, err
}
