// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadMessages = `-- name: CountUnreadMessages :one
SELECT COUNT(*) FROM messages WHERE recipient_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadMessages(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadMessages, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadMessagesForMatch = `-- name: CountUnreadMessagesForMatch :one
SELECT COUNT(*) FROM messages WHERE match_id = $1 AND recipient_id = $2 AND is_read = FALSE
`

type CountUnreadMessagesForMatchParams struct {
	MatchID     uuid.UUID `json:"match_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) CountUnreadMessagesForMatch(ctx context.Context, arg CountUnreadMessagesForMatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadMessagesForMatch, arg.MatchID, arg.RecipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    match_id,
    sender_id,
    recipient_id,
    content
) VALUES ($1, $2, $3, $4)
RETURNING id, match_id, sender_id, recipient_id, content, is_read, sent_at, read_at, updated_at
`

type CreateMessageParams struct {
	MatchID     uuid.UUID `json:"match_id"`
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
	Content     string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.MatchID,
		arg.SenderID,
		arg.RecipientID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.IsRead,
		&i.SentAt,
		&i.ReadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT DISTINCT ON (match_id) id, match_id, sender_id, recipient_id, content, is_read, sent_at, read_at, updated_at
FROM messages
WHERE sender_id = $1 OR recipient_id = $1
ORDER BY match_id, sent_at DESC
`

func (q *Queries) ListConversationsForUser(ctx context.Context, senderID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listConversationsForUser, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.IsRead,
			&i.SentAt,
			&i.ReadAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesForMatch = `-- name: ListMessagesForMatch :many
SELECT id, match_id, sender_id, recipient_id, content, is_read, sent_at, read_at, updated_at FROM messages WHERE match_id = $1 ORDER BY sent_at ASC
`

func (q *Queries) ListMessagesForMatch(ctx context.Context, matchID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesForMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.IsRead,
			&i.SentAt,
			&i.ReadAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesRead = `-- name: MarkMessagesRead :exec
UPDATE messages SET is_read = TRUE, read_at = NOW()
WHERE id = ANY($1::uuid[]) AND recipient_id = $2 AND is_read = FALSE
`

type MarkMessagesReadParams struct {
	Column1     []uuid.UUID `json:"column_1"`
	RecipientID uuid.UUID   `json:"recipient_id"`
}

func (q *Queries) MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesRead, arg.Column1, arg.RecipientID)
	return err
}
