// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSetting struct {
	ID           uuid.UUID   `json:"id"`
	SettingKey   string      `json:"setting_key"`
	SettingValue []byte      `json:"setting_value"`
	UpdatedAt    time.Time   `json:"updated_at"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

type Campaign struct {
	ID                     uuid.UUID   `json:"id"`
	Name                   string      `json:"name"`
	SurveyOpenDate         time.Time   `json:"survey_open_date"`
	SurveyCloseDate        time.Time   `json:"survey_close_date"`
	ProfileUpdateStartDate time.Time   `json:"profile_update_start_date"`
	ProfileUpdateEndDate   time.Time   `json:"profile_update_end_date"`
	ResultsReleaseDate     time.Time   `json:"results_release_date"`
	IsActive               pgtype.Bool `json:"is_active"`
	TotalParticipants      pgtype.Int4 `json:"total_participants"`
	TotalMatchesGenerated  pgtype.Int4 `json:"total_matches_generated"`
	AlgorithmVersion       pgtype.Text `json:"algorithm_version"`
	Config                 []byte      `json:"config"`
	CreatedAt              time.Time   `json:"created_at"`
}

type CrushList struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	CampaignID uuid.UUID   `json:"campaign_id"`
	CrushEmail string      `json:"crush_email"`
	CrushName  pgtype.Text `json:"crush_name"`
	IsMatched  bool        `json:"is_matched"`
	IsMutual   bool        `json:"is_mutual"`
	NudgeSent  bool        `json:"nudge_sent"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Interaction struct {
	ID              uuid.UUID `json:"id"`
	MatchID         uuid.UUID `json:"match_id"`
	UserID          uuid.UUID `json:"user_id"`
	InteractionType string    `json:"interaction_type"`
	Metadata        []byte    `json:"metadata"`
	CreatedAt       time.Time `json:"created_at"`
}

type Match struct {
	ID                 uuid.UUID          `json:"id"`
	CampaignID         pgtype.UUID        `json:"campaign_id"`
	User1ID            uuid.UUID          `json:"user1_id"`
	User2ID            uuid.UUID          `json:"user2_id"`
	CompatibilityScore pgtype.Numeric     `json:"compatibility_score"`
	MatchTier          pgtype.Text        `json:"match_tier"`
	SharedInterests    []byte             `json:"shared_interests"`
	RankForUser1       pgtype.Int4        `json:"rank_for_user1"`
	RankForUser2       pgtype.Int4        `json:"rank_for_user2"`
	IsRevealed         bool               `json:"is_revealed"`
	IsMutualInterest   bool               `json:"is_mutual_interest"`
	IsMutualCrush      bool               `json:"is_mutual_crush"`
	MessagingUnlocked  bool               `json:"messaging_unlocked"`
	CreatedAt          time.Time          `json:"created_at"`
	RevealedAt         pgtype.Timestamptz `json:"revealed_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type Message struct {
	ID          uuid.UUID          `json:"id"`
	MatchID     uuid.UUID          `json:"match_id"`
	SenderID    uuid.UUID          `json:"sender_id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	Content     string             `json:"content"`
	IsRead      bool               `json:"is_read"`
	SentAt      time.Time          `json:"sent_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type Question struct {
	ID           uuid.UUID      `json:"id"`
	CampaignID   pgtype.UUID    `json:"campaign_id"`
	Category     string         `json:"category"`
	QuestionText string         `json:"question_text"`
	QuestionType string         `json:"question_type"`
	Options      []byte         `json:"options"`
	Weight       pgtype.Numeric `json:"weight"`
	IsActive     bool           `json:"is_active"`
	OrderIndex   int32          `json:"order_index"`
	CreatedAt    time.Time      `json:"created_at"`
}

type SurveyResponse struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	CampaignID  pgtype.UUID `json:"campaign_id"`
	QuestionID  uuid.UUID   `json:"question_id"`
	AnswerText  pgtype.Text `json:"answer_text"`
	AnswerValue pgtype.Int4 `json:"answer_value"`
	AnswerJson  []byte      `json:"answer_json"`
	AnswerType  string      `json:"answer_type"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Testimonial struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Email       pgtype.Text `json:"email"`
	Heading     string      `json:"heading"`
	Content     string      `json:"content"`
	IsApproved  bool        `json:"is_approved"`
	IsPublished bool        `json:"is_published"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	GoogleID          pgtype.Text        `json:"google_id"`
	Username          pgtype.Text        `json:"username"`
	StudentID         pgtype.Text        `json:"student_id"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Program           pgtype.Text        `json:"program"`
	YearLevel         pgtype.Int4        `json:"year_level"`
	Gender            pgtype.Text        `json:"gender"`
	SeekingGender     pgtype.Text        `json:"seeking_gender"`
	DateOfBirth       pgtype.Date        `json:"date_of_birth"`
	ProfilePhotoUrl   pgtype.Text        `json:"profile_photo_url"`
	Bio               pgtype.Text        `json:"bio"`
	InstagramHandle   pgtype.Text        `json:"instagram_handle"`
	FacebookProfile   pgtype.Text        `json:"facebook_profile"`
	SocialMediaName   pgtype.Text        `json:"social_media_name"`
	PhoneNumber       pgtype.Text        `json:"phone_number"`
	ContactPreference pgtype.Text        `json:"contact_preference"`
	ProfileVisibility string             `json:"profile_visibility"`
	Preferences       []byte             `json:"preferences"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsActive          bool               `json:"is_active"`
	SurveyCompleted   bool               `json:"survey_completed"`
}
