// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: public.sql

package repository

import (
	"context"
)

const publicStats = `-- name: PublicStats :one
SELECT
    (SELECT COUNT(*) FROM users) AS total_users,
    (SELECT COUNT(*) FROM users WHERE survey_completed = TRUE) AS completed_surveys,
    (SELECT COUNT(*) FROM matches) AS total_matches
`

type PublicStatsRow struct {
	TotalUsers       int64 `json:"total_users"`
	CompletedSurveys int64 `json:"completed_surveys"`
	TotalMatches     int64 `json:"total_matches"`
}

func (q *Queries) PublicStats(ctx context.Context) (PublicStatsRow, error) {
	row := q.db.QueryRow(ctx, publicStats)
	var i PublicStatsRow
	err := row.Scan(&i.TotalUsers, &i.CompletedSurveys, &i.TotalMatches)
	return i, err
}
