// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AverageCompatibilityScore(ctx context.Context) (float64, error)
	AverageCompatibilityScoreByCampaign(ctx context.Context, campaignID pgtype.UUID) (float64, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountCompletedSurveys(ctx context.Context) (int64, error)
	CountCompletedSurveysByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CountCrushByUserEmailCampaign(ctx context.Context, arg CountCrushByUserEmailCampaignParams) (int64, error)
	CountMatches(ctx context.Context) (int64, error)
	CountMatchesAll(ctx context.Context) (int64, error)
	CountMatchesByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CountMutualMatches(ctx context.Context) (int64, error)
	CountMutualMatchesByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CountParticipantsByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CountRevealedMatches(ctx context.Context) (int64, error)
	CountRevealedMatchesByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CountUnreadMessages(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountUnreadMessagesForMatch(ctx context.Context, arg CountUnreadMessagesForMatchParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersSearch(ctx context.Context, firstName string) (int64, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateCrush(ctx context.Context, arg CreateCrushParams) (CrushList, error)
	CreateInteraction(ctx context.Context, arg CreateInteractionParams) (Interaction, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSurveyResponse(ctx context.Context, arg CreateSurveyResponseParams) (SurveyResponse, error)
	CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (Testimonial, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCampaign(ctx context.Context, id uuid.UUID) error
	DeleteCrushesForUserCampaign(ctx context.Context, arg DeleteCrushesForUserCampaignParams) error
	DeleteMatch(ctx context.Context, id uuid.UUID) error
	DeleteMatchesByCampaign(ctx context.Context, campaignID pgtype.UUID) error
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FindInterestByMatchOtherUser(ctx context.Context, arg FindInterestByMatchOtherUserParams) (Interaction, error)
	FindOrCreateMatchForUsers(ctx context.Context, arg FindOrCreateMatchForUsersParams) (Match, error)
	GetActiveCampaign(ctx context.Context) (Campaign, error)
	GetAdminSettingByKey(ctx context.Context, settingKey string) (AdminSetting, error)
	GetCampaignByID(ctx context.Context, id uuid.UUID) (Campaign, error)
	GetMatchByID(ctx context.Context, id uuid.UUID) (Match, error)
	GetMatchByUsers(ctx context.Context, arg GetMatchByUsersParams) (Match, error)
	GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListCampaigns(ctx context.Context) ([]Campaign, error)
	ListConversationsForUser(ctx context.Context, senderID uuid.UUID) ([]Message, error)
	ListCrushesByEmailCampaign(ctx context.Context, arg ListCrushesByEmailCampaignParams) ([]CrushList, error)
	ListCrushesForCampaign(ctx context.Context, campaignID uuid.UUID) ([]CrushList, error)
	ListCrushesForUserCampaign(ctx context.Context, arg ListCrushesForUserCampaignParams) ([]CrushList, error)
	ListEligibleUsers(ctx context.Context) ([]ListEligibleUsersRow, error)
	ListMatches(ctx context.Context, arg ListMatchesParams) ([]Match, error)
	ListMatchesForUser(ctx context.Context, user1ID uuid.UUID) ([]Match, error)
	ListMessagesForMatch(ctx context.Context, matchID uuid.UUID) ([]Message, error)
	ListPotentialMatches(ctx context.Context, id uuid.UUID) ([]ListPotentialMatchesRow, error)
	ListQuestions(ctx context.Context) ([]Question, error)
	ListSurveyResponsesByUser(ctx context.Context, userID uuid.UUID) ([]SurveyResponse, error)
	ListSurveyResponsesWithQuestionsByUserCampaign(ctx context.Context, arg ListSurveyResponsesWithQuestionsByUserCampaignParams) ([]ListSurveyResponsesWithQuestionsByUserCampaignRow, error)
	ListTestimonials(ctx context.Context) ([]Testimonial, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error)
	MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error
	MatchesByTier(ctx context.Context) ([]MatchesByTierRow, error)
	MatchesByTierByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]MatchesByTierByCampaignRow, error)
	ProgramsWithCompletion(ctx context.Context) ([]ProgramsWithCompletionRow, error)
	ProgramsWithCompletionByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]ProgramsWithCompletionByCampaignRow, error)
	PublicStats(ctx context.Context) (PublicStatsRow, error)
	RecordUserInteraction(ctx context.Context, arg RecordUserInteractionParams) (Interaction, error)
	RevealMatch(ctx context.Context, id uuid.UUID) (Match, error)
	SearchUsersAdmin(ctx context.Context, arg SearchUsersAdminParams) ([]SearchUsersAdminRow, error)
	SetUserSurveyCompleted(ctx context.Context, arg SetUserSurveyCompletedParams) error
	TopPrograms(ctx context.Context, limit int32) ([]TopProgramsRow, error)
	TopProgramsByCampaign(ctx context.Context, arg TopProgramsByCampaignParams) ([]TopProgramsByCampaignRow, error)
	UnlockMessagingByCampaign(ctx context.Context, campaignID pgtype.UUID) error
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateCampaignStats(ctx context.Context, arg UpdateCampaignStatsParams) error
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error)
	UpdateMatchInterest(ctx context.Context, arg UpdateMatchInterestParams) (Match, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateTestimonialApproval(ctx context.Context, arg UpdateTestimonialApprovalParams) (Testimonial, error)
	UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) (UpdateUserPhotoRow, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UpdateUserPreferencesRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertAdminSetting(ctx context.Context, arg UpsertAdminSettingParams) (AdminSetting, error)
	YearLevelsWithCompletion(ctx context.Context) ([]YearLevelsWithCompletionRow, error)
	YearLevelsWithCompletionByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]YearLevelsWithCompletionByCampaignRow, error)
}

var _ Querier = (*Queries)(nil)
