// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    campaign_id,
    category,
    question_text,
    question_type,
    options,
    weight,
    is_active,
    order_index
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, campaign_id, category, question_text, question_type, options, weight, is_active, order_index, created_at
`

type CreateQuestionParams struct {
	CampaignID   pgtype.UUID    `json:"campaign_id"`
	Category     string         `json:"category"`
	QuestionText string         `json:"question_text"`
	QuestionType string         `json:"question_type"`
	Options      []byte         `json:"options"`
	Weight       pgtype.Numeric `json:"weight"`
	IsActive     bool           `json:"is_active"`
	OrderIndex   int32          `json:"order_index"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.CampaignID,
		arg.Category,
		arg.QuestionText,
		arg.QuestionType,
		arg.Options,
		arg.Weight,
		arg.IsActive,
		arg.OrderIndex,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Category,
		&i.QuestionText,
		&i.QuestionType,
		&i.Options,
		&i.Weight,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET
    category = COALESCE($2, category),
    question_text = COALESCE($3, question_text),
    question_type = COALESCE($4, question_type),
    options = COALESCE($5, options),
    weight = COALESCE($6, weight),
    is_active = COALESCE($7, is_active),
    order_index = COALESCE(NULLIF($8, 0), order_index)
WHERE id = $1
RETURNING id, campaign_id, category, question_text, question_type, options, weight, is_active, order_index, created_at
`

type UpdateQuestionParams struct {
	ID           uuid.UUID      `json:"id"`
	Category     string         `json:"category"`
	QuestionText string         `json:"question_text"`
	QuestionType string         `json:"question_type"`
	Options      []byte         `json:"options"`
	Weight       pgtype.Numeric `json:"weight"`
	IsActive     bool           `json:"is_active"`
	Column8      interface{}    `json:"column_8"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Category,
		arg.QuestionText,
		arg.QuestionType,
		arg.Options,
		arg.Weight,
		arg.IsActive,
		arg.Column8,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Category,
		&i.QuestionText,
		&i.QuestionType,
		&i.Options,
		&i.Weight,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}
