// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: survey.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSurveyResponse = `-- name: CreateSurveyResponse :one
INSERT INTO survey_responses (
    user_id,
    campaign_id,
    question_id,
    answer_text,
    answer_value,
    answer_json,
    answer_type
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, question_id)
DO UPDATE SET
    answer_text = EXCLUDED.answer_text,
    answer_value = EXCLUDED.answer_value,
    answer_json = EXCLUDED.answer_json,
    answer_type = EXCLUDED.answer_type,
    updated_at = NOW()
RETURNING id, user_id, campaign_id, question_id, answer_text, answer_value, answer_json, answer_type, created_at, updated_at
`

type CreateSurveyResponseParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	CampaignID  pgtype.UUID `json:"campaign_id"`
	QuestionID  uuid.UUID   `json:"question_id"`
	AnswerText  pgtype.Text `json:"answer_text"`
	AnswerValue pgtype.Int4 `json:"answer_value"`
	AnswerJson  []byte      `json:"answer_json"`
	AnswerType  string      `json:"answer_type"`
}

func (q *Queries) CreateSurveyResponse(ctx context.Context, arg CreateSurveyResponseParams) (SurveyResponse, error) {
	row := q.db.QueryRow(ctx, createSurveyResponse,
		arg.UserID,
		arg.CampaignID,
		arg.QuestionID,
		arg.AnswerText,
		arg.AnswerValue,
		arg.AnswerJson,
		arg.AnswerType,
	)
	var i SurveyResponse
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.QuestionID,
		&i.AnswerText,
		&i.AnswerValue,
		&i.AnswerJson,
		&i.AnswerType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, campaign_id, category, question_text, question_type, options, weight, is_active, order_index, created_at FROM questions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Category,
		&i.QuestionText,
		&i.QuestionType,
		&i.Options,
		&i.Weight,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, campaign_id, category, question_text, question_type, options, weight, is_active, order_index, created_at FROM questions WHERE is_active = TRUE ORDER BY order_index ASC
`

func (q *Queries) ListQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Category,
			&i.QuestionText,
			&i.QuestionType,
			&i.Options,
			&i.Weight,
			&i.IsActive,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveyResponsesByUser = `-- name: ListSurveyResponsesByUser :many
SELECT id, user_id, campaign_id, question_id, answer_text, answer_value, answer_json, answer_type, created_at, updated_at FROM survey_responses WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListSurveyResponsesByUser(ctx context.Context, userID uuid.UUID) ([]SurveyResponse, error) {
	rows, err := q.db.Query(ctx, listSurveyResponsesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyResponse{}
	for rows.Next() {
		var i SurveyResponse
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CampaignID,
			&i.QuestionID,
			&i.AnswerText,
			&i.AnswerValue,
			&i.AnswerJson,
			&i.AnswerType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
