// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersSearch = `-- name: CountUsersSearch :one
SELECT COUNT(*) FROM users
WHERE first_name ILIKE $1 OR last_name ILIKE $1 OR email ILIKE $1 OR student_id ILIKE $1
`

func (q *Queries) CountUsersSearch(ctx context.Context, firstName string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersSearch, firstName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    google_id,
    username,
    student_id,
    first_name,
    last_name,
    program,
    year_level,
    gender,
    seeking_gender,
    date_of_birth,
    profile_photo_url,
    bio,
    instagram_handle,
    facebook_profile,
    social_media_name,
    phone_number,
    contact_preference,
    profile_visibility,
    preferences,
    last_login,
    is_active,
    survey_completed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
) RETURNING id, email, google_id, username, student_id, first_name, last_name, program, year_level, gender, seeking_gender, date_of_birth, profile_photo_url, bio, instagram_handle, facebook_profile, social_media_name, phone_number, contact_preference, profile_visibility, preferences, created_at, updated_at, last_login, is_active, survey_completed
`

type CreateUserParams struct {
	Email             string             `json:"email"`
	GoogleID          pgtype.Text        `json:"google_id"`
	Username          pgtype.Text        `json:"username"`
	StudentID         pgtype.Text        `json:"student_id"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Program           pgtype.Text        `json:"program"`
	YearLevel         pgtype.Int4        `json:"year_level"`
	Gender            pgtype.Text        `json:"gender"`
	SeekingGender     pgtype.Text        `json:"seeking_gender"`
	DateOfBirth       pgtype.Date        `json:"date_of_birth"`
	ProfilePhotoUrl   pgtype.Text        `json:"profile_photo_url"`
	Bio               pgtype.Text        `json:"bio"`
	InstagramHandle   pgtype.Text        `json:"instagram_handle"`
	FacebookProfile   pgtype.Text        `json:"facebook_profile"`
	SocialMediaName   pgtype.Text        `json:"social_media_name"`
	PhoneNumber       pgtype.Text        `json:"phone_number"`
	ContactPreference pgtype.Text        `json:"contact_preference"`
	ProfileVisibility string             `json:"profile_visibility"`
	Preferences       []byte             `json:"preferences"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsActive          bool               `json:"is_active"`
	SurveyCompleted   bool               `json:"survey_completed"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.GoogleID,
		arg.Username,
		arg.StudentID,
		arg.FirstName,
		arg.LastName,
		arg.Program,
		arg.YearLevel,
		arg.Gender,
		arg.SeekingGender,
		arg.DateOfBirth,
		arg.ProfilePhotoUrl,
		arg.Bio,
		arg.InstagramHandle,
		arg.FacebookProfile,
		arg.SocialMediaName,
		arg.PhoneNumber,
		arg.ContactPreference,
		arg.ProfileVisibility,
		arg.Preferences,
		arg.LastLogin,
		arg.IsActive,
		arg.SurveyCompleted,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Program,
		&i.YearLevel,
		&i.Gender,
		&i.SeekingGender,
		&i.DateOfBirth,
		&i.ProfilePhotoUrl,
		&i.Bio,
		&i.InstagramHandle,
		&i.FacebookProfile,
		&i.SocialMediaName,
		&i.PhoneNumber,
		&i.ContactPreference,
		&i.ProfileVisibility,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.IsActive,
		&i.SurveyCompleted,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, google_id, username, student_id, first_name, last_name, program, year_level, gender, seeking_gender, date_of_birth, profile_photo_url, bio, instagram_handle, facebook_profile, social_media_name, phone_number, contact_preference, profile_visibility, preferences, created_at, updated_at, last_login, is_active, survey_completed FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Program,
		&i.YearLevel,
		&i.Gender,
		&i.SeekingGender,
		&i.DateOfBirth,
		&i.ProfilePhotoUrl,
		&i.Bio,
		&i.InstagramHandle,
		&i.FacebookProfile,
		&i.SocialMediaName,
		&i.PhoneNumber,
		&i.ContactPreference,
		&i.ProfileVisibility,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.IsActive,
		&i.SurveyCompleted,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, google_id, username, student_id, first_name, last_name, program, year_level, gender, seeking_gender, date_of_birth, profile_photo_url, bio, instagram_handle, facebook_profile, social_media_name, phone_number, contact_preference, profile_visibility, preferences, created_at, updated_at, last_login, is_active, survey_completed FROM users WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Program,
		&i.YearLevel,
		&i.Gender,
		&i.SeekingGender,
		&i.DateOfBirth,
		&i.ProfilePhotoUrl,
		&i.Bio,
		&i.InstagramHandle,
		&i.FacebookProfile,
		&i.SocialMediaName,
		&i.PhoneNumber,
		&i.ContactPreference,
		&i.ProfileVisibility,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.IsActive,
		&i.SurveyCompleted,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, google_id, username, student_id, first_name, last_name, program, year_level, gender, seeking_gender, date_of_birth, profile_photo_url, bio, instagram_handle, facebook_profile, social_media_name, phone_number, contact_preference, profile_visibility, preferences, created_at, updated_at, last_login, is_active, survey_completed FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Program,
		&i.YearLevel,
		&i.Gender,
		&i.SeekingGender,
		&i.DateOfBirth,
		&i.ProfilePhotoUrl,
		&i.Bio,
		&i.InstagramHandle,
		&i.FacebookProfile,
		&i.SocialMediaName,
		&i.PhoneNumber,
		&i.ContactPreference,
		&i.ProfileVisibility,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.IsActive,
		&i.SurveyCompleted,
	)
	return i, err
}

const listEligibleUsers = `-- name: ListEligibleUsers :many
SELECT id, email, first_name, last_name, program, year_level, gender, seeking_gender
FROM users
WHERE survey_completed = TRUE AND is_active = TRUE
ORDER BY first_name ASC
`

type ListEligibleUsersRow struct {
	ID            uuid.UUID   `json:"id"`
	Email         string      `json:"email"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Program       pgtype.Text `json:"program"`
	YearLevel     pgtype.Int4 `json:"year_level"`
	Gender        pgtype.Text `json:"gender"`
	SeekingGender pgtype.Text `json:"seeking_gender"`
}

func (q *Queries) ListEligibleUsers(ctx context.Context) ([]ListEligibleUsersRow, error) {
	rows, err := q.db.Query(ctx, listEligibleUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligibleUsersRow{}
	for rows.Next() {
		var i ListEligibleUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Program,
			&i.YearLevel,
			&i.Gender,
			&i.SeekingGender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT id, email, student_id, first_name, last_name, program, year_level, survey_completed, is_active, created_at, last_login
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersAdminRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	StudentID       pgtype.Text        `json:"student_id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Program         pgtype.Text        `json:"program"`
	YearLevel       pgtype.Int4        `json:"year_level"`
	SurveyCompleted bool               `json:"survey_completed"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       time.Time          `json:"created_at"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAdminRow{}
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Program,
			&i.YearLevel,
			&i.SurveyCompleted,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersAdmin = `-- name: SearchUsersAdmin :many
SELECT id, email, student_id, first_name, last_name, program, year_level, survey_completed, is_active, created_at, last_login
FROM users
WHERE first_name ILIKE $1 OR last_name ILIKE $1 OR email ILIKE $1 OR student_id ILIKE $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersAdminParams struct {
	FirstName string `json:"first_name"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type SearchUsersAdminRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	StudentID       pgtype.Text        `json:"student_id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Program         pgtype.Text        `json:"program"`
	YearLevel       pgtype.Int4        `json:"year_level"`
	SurveyCompleted bool               `json:"survey_completed"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       time.Time          `json:"created_at"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) SearchUsersAdmin(ctx context.Context, arg SearchUsersAdminParams) ([]SearchUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdmin, arg.FirstName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersAdminRow{}
	for rows.Next() {
		var i SearchUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Program,
			&i.YearLevel,
			&i.SurveyCompleted,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSurveyCompleted = `-- name: SetUserSurveyCompleted :exec
UPDATE users SET survey_completed = $2, updated_at = NOW() WHERE id = $1
`

type SetUserSurveyCompletedParams struct {
	ID              uuid.UUID `json:"id"`
	SurveyCompleted bool      `json:"survey_completed"`
}

func (q *Queries) SetUserSurveyCompleted(ctx context.Context, arg SetUserSurveyCompletedParams) error {
	_, err := q.db.Exec(ctx, setUserSurveyCompleted, arg.ID, arg.SurveyCompleted)
	return err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
UPDATE users SET
    email = COALESCE($2, email),
    first_name = COALESCE($3, first_name),
    last_name = COALESCE($4, last_name),
    program = COALESCE($5, program),
    year_level = COALESCE($6, year_level),
    survey_completed = COALESCE($7, survey_completed),
    is_active = COALESCE($8, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, google_id, username, student_id, first_name, last_name, program, year_level, gender, seeking_gender, date_of_birth, profile_photo_url, bio, instagram_handle, facebook_profile, social_media_name, phone_number, contact_preference, profile_visibility, preferences, created_at, updated_at, last_login, is_active, survey_completed
`

type UpdateUserAdminParams struct {
	ID              uuid.UUID   `json:"id"`
	Email           string      `json:"email"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	Program         pgtype.Text `json:"program"`
	YearLevel       pgtype.Int4 `json:"year_level"`
	SurveyCompleted bool        `json:"survey_completed"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Program,
		arg.YearLevel,
		arg.SurveyCompleted,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Program,
		&i.YearLevel,
		&i.Gender,
		&i.SeekingGender,
		&i.DateOfBirth,
		&i.ProfilePhotoUrl,
		&i.Bio,
		&i.InstagramHandle,
		&i.FacebookProfile,
		&i.SocialMediaName,
		&i.PhoneNumber,
		&i.ContactPreference,
		&i.ProfileVisibility,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.IsActive,
		&i.SurveyCompleted,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPhoto = `-- name: UpdateUserPhoto :one
UPDATE users SET
    profile_photo_url = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, profile_photo_url
`

type UpdateUserPhotoParams struct {
	ID              uuid.UUID   `json:"id"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
}

type UpdateUserPhotoRow struct {
	ID              uuid.UUID   `json:"id"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
}

func (q *Queries) UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) (UpdateUserPhotoRow, error) {
	row := q.db.QueryRow(ctx, updateUserPhoto, arg.ID, arg.ProfilePhotoUrl)
	var i UpdateUserPhotoRow
	err := row.Scan(&i.ID, &i.ProfilePhotoUrl)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users SET
    preferences = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, preferences
`

type UpdateUserPreferencesParams struct {
	ID          uuid.UUID `json:"id"`
	Preferences []byte    `json:"preferences"`
}

type UpdateUserPreferencesRow struct {
	ID          uuid.UUID `json:"id"`
	Preferences []byte    `json:"preferences"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UpdateUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences, arg.ID, arg.Preferences)
	var i UpdateUserPreferencesRow
	err := row.Scan(&i.ID, &i.Preferences)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    first_name = COALESCE(NULLIF($2, ''), first_name),
    last_name = COALESCE(NULLIF($3, ''), last_name),
    program = COALESCE($4, program),
    year_level = COALESCE($5, year_level),
    gender = COALESCE($6, gender),
    seeking_gender = COALESCE($7, seeking_gender),
    date_of_birth = COALESCE($8, date_of_birth),
    profile_photo_url = COALESCE($9, profile_photo_url),
    bio = COALESCE($10, bio),
    instagram_handle = COALESCE($11, instagram_handle),
    facebook_profile = COALESCE($12, facebook_profile),
    social_media_name = COALESCE($13, social_media_name),
    phone_number = COALESCE($14, phone_number),
    contact_preference = COALESCE($15, contact_preference),
    profile_visibility = COALESCE(NULLIF($16, ''), profile_visibility),
    preferences = COALESCE($17, preferences),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, google_id, username, student_id, first_name, last_name, program, year_level, gender, seeking_gender, date_of_birth, profile_photo_url, bio, instagram_handle, facebook_profile, social_media_name, phone_number, contact_preference, profile_visibility, preferences, created_at, updated_at, last_login, is_active, survey_completed
`

type UpdateUserProfileParams struct {
	ID                uuid.UUID   `json:"id"`
	Column2           interface{} `json:"column_2"`
	Column3           interface{} `json:"column_3"`
	Program           pgtype.Text `json:"program"`
	YearLevel         pgtype.Int4 `json:"year_level"`
	Gender            pgtype.Text `json:"gender"`
	SeekingGender     pgtype.Text `json:"seeking_gender"`
	DateOfBirth       pgtype.Date `json:"date_of_birth"`
	ProfilePhotoUrl   pgtype.Text `json:"profile_photo_url"`
	Bio               pgtype.Text `json:"bio"`
	InstagramHandle   pgtype.Text `json:"instagram_handle"`
	FacebookProfile   pgtype.Text `json:"facebook_profile"`
	SocialMediaName   pgtype.Text `json:"social_media_name"`
	PhoneNumber       pgtype.Text `json:"phone_number"`
	ContactPreference pgtype.Text `json:"contact_preference"`
	Column16          interface{} `json:"column_16"`
	Preferences       []byte      `json:"preferences"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Program,
		arg.YearLevel,
		arg.Gender,
		arg.SeekingGender,
		arg.DateOfBirth,
		arg.ProfilePhotoUrl,
		arg.Bio,
		arg.InstagramHandle,
		arg.FacebookProfile,
		arg.SocialMediaName,
		arg.PhoneNumber,
		arg.ContactPreference,
		arg.Column16,
		arg.Preferences,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Program,
		&i.YearLevel,
		&i.Gender,
		&i.SeekingGender,
		&i.DateOfBirth,
		&i.ProfilePhotoUrl,
		&i.Bio,
		&i.InstagramHandle,
		&i.FacebookProfile,
		&i.SocialMediaName,
		&i.PhoneNumber,
		&i.ContactPreference,
		&i.ProfileVisibility,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.IsActive,
		&i.SurveyCompleted,
	)
	return i, err
}
